### ISSUE TITLE
[FEATURE] export a cacache reference

### ISSUE THREAD

**Issue by ilg-ul** [npm/pacote#21]
# What / Why

For consistency reasons, I think that it would be useful to re-export a reference to the current cacache module.

My application uses pacote for fetching packages, and cacache for fetching archives with binary tools referred by the packages.

Currently I have dependencies to both pacote and cacache, but, for consistency reasons, with each version bump, I have to manually check the version of cacache used by pacote, and configure my dependencies accordingly.

Knowing your code you might not agree, but generally I think that using two different versions of a cache manager in the same folder may be unsafe, or, if the code is 100% able to cure/recover the content, at least inefficient, since a new version may write content in a format that the old version might not like and each access run a full content cache.

The changes to accommodate this feature are minimal, for example a new line in `index.js` like:

```js
module.exports = {
  resolve: (spec, opts) => get(spec, opts).resolve(),
  extract: (spec, dest, opts) => get(spec, opts).extract(dest),
  manifest: (spec, opts) => get(spec, opts).manifest(),
  tarball: (spec, opts) => get(spec, opts).tarball(),
  packument: (spec, opts) => get(spec, opts).packument(),
  cacache: require('cacache'), // <---
}
```

With such a definition, my application would no longer need a dependency to cacache, and get it from pacote.

**Comment by ilg-ul** [comment]
Any opinion on this suggestion? Is it useless? Is it stupid? Do you foresee any dangers? 

I'm now at the point of updating the dependencies for my application, and each time I need to check the version of `cacache` used by `pacote`, and be sure I use the same.

It is not rocket science, but it just increases the maintenance efforts.

**Comment by wraithgar** [comment]
This is a class of problems usually solved with `peerDependencies`, not by exporting dependencies up the chain.

Additionally pacote is not the only consumer of `cacache` here, under the hood `make-fetch-happen` is what ends up being used to fetch things from the registry, and both modules use the same cacache semver major.

However, I don't think we are planning on adding cacache as a peer dependency to these projects.  The dependency tree is pretty tightly coupled between all of these modules, and consumers will want to check for semver major bumps to see if `cacache` was what changed.
