### ISSUE TITLE
[BUG] Unlimited concurrent connections are opened when using http proxy

### ISSUE THREAD

**Issue by shartte** [npm/pacote#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using a http-proxy to connect to a private registry.

(By setting https-proxy = http://someproxy:3128 in npmrc).

When running npm ci, I run into "503 too many connection" errors. After investigating, it turns out that the maxsockets option which npm passes to this lib has no effect if a proxy is used. I verified this by setting  DEBUG=https-proxy-agent:agent and running `npm:ci`. I can observe that the library opens 1700+ connections before the first one is closed again.

### Expected Behavior

I'd expect the library to respect maxsockets when using a HTTP proxy.

### Steps To Reproduce

1. Use any http proxy with a connection limit
2. Run `npm ci` (or any other large resolve action)
3. Observe the connection limits being exceeded

### Environment

- npm: 9.3.1
- Node: v18.13.0
- OS: Windows (this happens on Linux / our CI/CD too)
- platform: Dell Laptop & CI/CD Servers

**Comment by wraithgar** [comment]
This is a known issue and is being addressed by https://github.com/npm/statusboard/issues/584
