### ISSUE TITLE
How to use extract with a +git resolver ?

### ISSUE THREAD

**Issue by fraxken** [npm/pacote#3]
Hi,

I'm working on a Node.js security project where i download and extract npm packages with pacote (work very well). But sometimes users give custom resolvers (like git+). But right now i can't success to extract these.

I'm working on this given package.json: https://github.com/Purexo/html-to-rss/blob/master/package.json

With this as dependency
```
"u-http-server": "git+https://github.com/tpoisseau/uNodeHttpServer.git#1.0.1"
```

I'v tried a lot of syntax but everything fail.. Maybe is not supported, maybe i'm not doing the right thing so i'm coming here to get your feedback.

(i'v just created a little code to work on the subject.. like i said i tried many different URL).

```js
"use strict";
const pacote = require("pacote");

async function main() {
    const ret = await pacote.extract("https://github.com/tpoisseau/uNodeHttpServer.git#1.0.1", "./tmp");
    console.log(ret);
}
main().catch(console.error);
```

The README say `It supports all package specifier syntax that npm install and its ilk support.` so i supposed i'v missed something :\

Thanks for your time and help

Best Regards,
Thomas

**Comment by isaacs** [comment]
In order to extract git targets, you need to provide it a `cache` option currently.  like this:

```js
    const ret = await pacote.extract("https://github.com/tpoisseau/uNodeHttpServer.git#1.0.1", "./tmp", {
      cache: process.env.HOME + '/.npm'
    });
```

**Comment by isaacs** [comment]
Added the UX issue as https://github.com/npm/pacote/issues/5.

It'd be better if it told you that earlier, so you didn't have to come here wondering :)
