### ISSUE TITLE
`before` doesn't work without `fullMetadata`

### ISSUE THREAD

**Issue by altano** [npm/pacote#30]
The _undocumented_ `fullMetadata` option is required to fetch times, and without this the `before` flag appears to not work.

Repro:

```
$ npm view safe-write-stream time 
{
  ...
  '1.0.4': '2016-02-07T00:21:03.628Z', <=== Expected when specifying before: 2017-01-01
  '1.0.5': '2017-02-09T03:26:22.308Z'
}
```

**fullMetadata: undefined**
`node -e "require('pacote').manifest('safe-write-stream@^1.0.4', { before: new Date('2017-01-01') }).then(r => console.log(r.version));"`
Result: 1.0.5 ❌

**fullMetadata: false**
`node -e "require('pacote').manifest('safe-write-stream@^1.0.4', { fullMetadata: true, before: new Date('2017-01-01') }).then(r => console.log(r.version));"`
Result: 1.0.4 ✔

**Comment by isaacs** [comment]
Ahh!! Ok, we looked at this and initially thought it was already fixed, but it turns out even though we're setting `this.fullMetadata` based on a `before` option, that flag is not making its way back to the options passed to npm-registry-fetch.  Fix coming shortly.

**Comment by altano** [comment]
Amazingly fast turnaround, thanks!

**Comment by isaacs** [comment]
It helps that you posted a bug on a module that we're currently in the midst of editing for other reasons  😆

**Comment by altano** [comment]
Makes sense. I’ll make sure to only find bugs in actively developed projects from now on. :p
