### ISSUE TITLE
[BUG] subdependency move-file only supports node >= 10.17

### ISSUE THREAD

**Issue by BigsonLvrocha** [npm/pacote#41]
# What / Why

I can't upgrade a package depending of this package since I was using the same version of node (1.16.1) that the server uses, but it just throws an error that is hard to trace because incompatibility is in a subdependency.

The depedency path is pacote > cacache > move-file

## When
When I run install in server

## Where

* n/a

### Current Behavior
yarn throws error that move-file is not compatible

### Steps to Reproduce
just run
```sh
nvm use 10.16
yarn install
```

### Expected Behavior
if cacache is really needed, then update node engine constraint to >= 10.17

## References
Related to https://github.com/raineorshine/npm-check-updates/issues/651
Broken by https://github.com/sindresorhus/move-file/pull/8

**Comment by isaacs** [comment]
No longer relevant, now that cacache uses `@npmcli/move-file` instead.
