### ISSUE TITLE
[BUG] pacote.extract resolves to the wrong value

### ISSUE THREAD

**Issue by jdmarshall** [npm/pacote#48]
# What / Why

> pacote.extract is documented as returning a `Promise<Object>`, instead it is returning a `Promise<boolean>`

## When

* always

## Where

* private registry

### Current Behavior

* returns false

### Steps to Reproduce

        
    let reply = await pacote.extract(src, tmpDir.path, args.options);

    console.log(reply);

output:
false

### Expected Behavior

* as documented in the readme, this should return an Object

## Who

* n/a

## References

* n/a

**Comment by isaacs** [comment]
What spec are you using that's creating this result?  I can't reproduce it.

**Comment by jdmarshall** [comment]
Inter-version behavioral change
