### ISSUE TITLE
[QUESTION] Reading relative dependecies

### ISSUE THREAD

**Issue by GMartigny** [npm/pacote#51]
# What / Why
When tracking down the cause of https://github.com/npm/cli/issues/1756, I found that `pacote` tries to read the `package.json` file of relative dependency (aka: local dependency).
Given a package `main` with a `package.json` as follow:
```json
{
	"name": "main",
	"dependencies": {
		"child": "file:./packages/child"
	}
}
```
In this case, reading `node_modules/main/packages/child/package.json` when installing `main` is bound to fail given that `main` is not yet installed.
One workaround could be to install such dependencies in a `"postinstall"` script. This feels a bit hacky however.

Am I doing things wrong or is it a genuine issue ?

## Where
Wherever

## Who
	npm install gmartigny-local-dep

## References
 * Related to https://github.com/npm/cli/issues/1756

**Comment by isaacs** [comment]
I'm having a hard time reproducing this on npm v7.  Can you provide a reproduction case that demonstrates the failure?  Happy to reopen if it's still a problem.

**Comment by GMartigny** [comment]
It was reproductible on NPM@6 at the time. But indeed, NPM@7 don't have the issue.
