### ISSUE TITLE
[BUG] When using git+ssh protocol, ~/.ssh/config isn't read

### ISSUE THREAD

**Issue by sunknudsen** [npm/pacote#60]
# What / Why

I use GitHub deploy keys for authentication when deploying private npm packages (using releases).

```console
$ cat ~/.ssh/config
Host react-hash-link
HostName github.com
IdentityFile ~/.ssh/react-hash-link
```

Running `npm install git+ssh://git@react-hash-link:sunknudsen/react-hash-link.git` works as expected, but not the following.

```console
$ pacote packument git+ssh://git@react-hash-link:sunknudsen/react-hash-link.git
TypeError [ERR_INVALID_URL]: Invalid URL: git+ssh://git@react-hash-link:sunknudsen/react-hash-link.git
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at new URL (internal/url.js:330:22)
    at GitFetcher.[_addGitSha] (/usr/local/lib/node_modules/pacote/lib/git.js:128:28)
    at /usr/local/lib/node_modules/pacote/lib/git.js:228:27 {
  input: 'git+ssh://git@react-hash-link:sunknudsen/react-hash-link.git',
  code: 'ERR_INVALID_URL'
}
```

This causes a downstream [issue](https://github.com/raineorshine/npm-check-updates/issues/788) with [npm-check-updates](https://github.com/raineorshine/npm-check-updates).

Perhaps I am missing something.

Thanks for your help!

**Comment by T-vK** [comment]
I think I'm getting a related error during `npm i --verbose` in a private project:

```
npm verb stack Error: exited with error code: 128
npm verb stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v12.20.0/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
npm verb stack     at ChildProcess.emit (events.js:314:20)
npm verb stack     at maybeClose (internal/child_process.js:1022:16)
npm verb stack     at Socket.<anonymous> (internal/child_process.js:444:11)
npm verb stack     at Socket.emit (events.js:314:20)
npm verb stack     at Pipe.<anonymous> (net.js:675:12)
npm verb cwd /builds/projects/my-project
npm verb Linux 3.10.0-1127.19.1.el7.x86_64
npm verb argv "/usr/local/nvm/versions/node/v12.20.0/bin/node" "/node_bin/npm" "ci" "--verbose" "--unsafe-perm=true" "--registry=http://private-registry/repository/ais-npm/"
npm verb node v12.20.0
npm verb npm  v6.14.9
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/bahmutov/local-or-home-npmrc.git
npm ERR! 
npm ERR! Warning: Permanently added 'github.com,140.82.121.3' (RSA) to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
npm verb exit [ 1, true ]
```

Not sure where it comes from because pacote is not a direct dependency.

**Comment by raineorshine** [comment]
@T-vK You may want to open a new issue. This issue is specifically for when `npm install` works but `pacote packument` doesn't.

Your issue appears to be an authentication issue with `git ls-remote`.

**Comment by sunknudsen** [comment]
Hey @isaacs,

I deleted `npm_modules` and `package-lock.json` from a project to clean install everything and now `npm` is failing.

```console
$ npm install git+ssh://git@react-hash-link:sunknudsen/react-hash-link.git
npm ERR! code ERR_INVALID_URL
npm ERR! Invalid URL: git+ssh://git@react-hash-link:sunknudsen/react-hash-link.git

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunknudsen/.npm/_logs/2021-02-05T15_42_29_710Z-debug.log
```

This is a pretty big deal for anyone using SSH and private GitHub repos to distribute private packages.

Perhaps I am doing something wrong at my end? I could really use a hand on this one. 🙏

**Comment by sunknudsen** [comment]
Hey @ruyadorno,

I see you just published version `11.2.6`.

Any chance someone at npm could have a look at this issue?

Sorry for the shout-outs, but things are horribly broken at the moment.

Could really use some feedback on this issue. 🙏

**Comment by sunknudsen** [comment]
I tried running `GIT_SSH_COMMAND="ssh -i ~/.ssh/react-hash-link" npm install git+ssh://git@github.com:sunknudsen/react-hash-link.git` and the command hung indefinitely.

Btw, even if this approach worked, it wouldn't work to deploy a project using `npm install` (given public keys can only be used once as a deploy key on GitHub) hence why I use the `.ssh/config` approach.

**Comment by isaacs** [comment]
So, I take it that the `react-hash-link` host is defined in `.ssh/config` to log into `github.com` with some specific key?

I think the issue here is that we're using `new URL(..)` to parse out the git url, because `url.parse()` is deprecated.  That's where the `ERR_INVALID_URL` is coming from.  I seem to recall that we'd done something to make the scp-style URLs work properly, maybe in the most recent publish?  (cc: @nlf)

Maybe we're not fixing this one up properly?  Does it work if you replace the `:` with a `/`?

**Comment by sunknudsen** [comment]
Good morning @isaacs,

Thanks so much for looking into this.

> Does it work if you replace the `:` with a `/`?

Yes! I confirm both `pacote packument git+ssh://git@react-hash-link/sunknudsen/react-hash-link.git` and `npm install git+ssh://git@react-hash-link/sunknudsen/react-hash-link.git` worked.

Is this the syntax we should use moving forward?

Best,

Sun
